apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: InfrastructureProvider
metadata:
  name: hetzner
spec:
  version: v1.1.6
  fetchConfig:
    url: https://github.com/syself/cluster-api-provider-hetzner/releases/download/v1.1.6/infrastructure-components.yaml
  # Use custom CAPH image with diagnostics flags support
  deployment:
    containers:
      - name: manager
        imageUrl: ghcr.io/enopax/images/caph:{{ .Chart.AppVersion }}