apiVersion: k0rdent.mirantis.com/v1beta1
kind: ProviderInterface
metadata:
  name: cluster-api-provider-hetzner
  labels:
    helm.toolkit.fluxcd.io/name: cluster-api-provider-hetzner
    helm.toolkit.fluxcd.io/namespace: kcm-system
  annotations:
    helm.sh/resource-policy: keep
spec:
  clusterGVKs:
    - group: infrastructure.cluster.x-k8s.io
      version: v1beta1
      kind: HetznerCluster
  clusterIdentities:
    - group: ""
      version: v1
      kind: Secret
  description: "Hetzner infrastructure provider for Cluster API"
